# Site settings
title: "Ruby on Rails Development, Newcastle upon Tyne"
email: jamie@codethisway.com
description: "Jamie Barton specialises in Ruby on Rails 3 & 4, AngularJS, CoffeeScript, SCSS, RSpec and building APIs."
baseurl: ""
url: "http://codethisway.com"
timezone: Europe/London
googlytics: 39558466-1

# Build settings
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title/
comments: true
