# Site settings
title: "Ruby on Rails Development, Newcastle upon Tyne"
email: jamie@codethisway.com
description: "Code This Way specialises in Ruby on Rails 3 & 4 web applications using AngularJS, CoffeeScript, SCSS, RSpec and APIs."
baseurl: ""
url: "http://codethisway.com"
timezone: Europe/London
googlytics: 39558466-1

# Build settings
markdown: rdiscount
permalink: pretty
